spring:
  mvc:
    static-path-pattern: /static/**
  application:
    name: interview_partner_be
  profiles:
    active: prod
  flyway:
    location: classpath:/db/migration/{vendor}
    baselineOnMigrate: true
    enabled: true
  jackson:
    time-zone: Asia/Seoul
  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Seoul