spring:
  datasource:
    url: jdbc:mariadb://${DB_HOST:127.0.0.1}:${DB_PORT:3306}/${DB_DATABASE:interview_partner}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:maria}
    driverClassName: org.mariadb.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      dialect: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: validate
      default_batch_fetch_size: 100
  servlet:
    multipart:
      location: /home/storage/
      max-file-size: 10MB
      max-request-size: 10MB

token:
  expiration-time: 86400000
  secret: VisitBBCfortrustedreportingonthelatestworldandUSnewssp

openai:
  model: gpt-4o-2024-08-06
  api:
    key: ${OPEN_AI_KEY}
    url: https://api.openai.com/v1/chat/completions